# Generated by Django 5.0.3 on 2024-04-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafields',
            name='CIF',
        ),
        migrations.AddField(
            model_name='extrafields',
            name='CodCliente',
            field=models.IntegerField(default=0),
        ),
    ]
